### ISSUE TITLE
Support SQL SERVER

### ISSUE THREAD

**Issue by IsaacSee** [sodadata/soda-sql#102]

**Comment by tombaeyens** [comment]
Hi IsaacSee, Tnx for your message.  Good to know that this is needed.  And this is a great place for others to vote for Soda SQL support.

As a follow on question: Would you be able to help with SQL Server support?  If you're able to translate the SQL's we currently produce for SQL Server, it will be easier for us to add support for it and we can deliver it faster.

**Comment by IsaacSee** [comment]
Hi @tombaeyens thanks for your quick answer. We are still evaluating soda-sql but it looks pretty awesome :)
We'll see how to contribute :)

**Comment by vijaykiran** [comment]
@IsaacSee  see https://github.com/sodadata/soda-sql/pull/120 :)

**Comment by IsaacSee** [comment]
Sweet! Thanks :)
