### ISSUE TITLE
Loosen Install Requirements

### ISSUE THREAD

**Issue by chriscardillo** [sodadata/soda-sql#176]
**Is your feature request related to a problem? Please describe.**
As mentioned in [this discussion](https://github.com/sodadata/soda-sql/discussions/172#discussion-3272988), Soda's install requirements are extremely rigid and pin users to older versions of sometimes critical packages (e.g the need to explicitly install `cryptography==3.3.2` when a newer minor release is available).

**Describe the solution you'd like**
The install requirements listed in `setup.py` should be more flexible.

**Additional context**
The three largest red flags I had while adjusting my requirements to meet Soda's needs were:

- cryptography
- the suite of Azure packages
- AWS boto related packages

I am sure some of this is stemming from your (awesome and legitimate) dependency on Snowflake's `snowflake-connector-python` package. Anywhere you're getting some nice abstraction for free, it's good if that abstraction can be responsible for its dependencies instead of you :smile: 

**Soda SQL Version**: 2.0.021b

**Comment by chriscardillo** [comment]
Did some digging into the modules and I am seeing the following dependencies (forgive the not perfect package names but I am sure you know what you are using!)

```
cli
- click
- yaml/PyYaml

scan
- boto3
- jinja2
 
soda_server_client
- requests

dialects
- boto3
- pyathena
- pyodbc
- snowflake (connector?)
- psycopg2
- pyhive
- thrift
- google
```

**Comment by tombaeyens** [comment]
@vijaykiran is in the process of splitting up the project into modules.  Once he s done (expected next week) he should be able to comment to what extend this loosening of the requirements has already been addressed or if we plan to do it later.

**Comment by chriscardillo** [comment]
I'd say the release of 2.1.0b1 can successfully close this issue!!

**Comment by vijaykiran** [comment]
Hey Chris, I think I made pretty much all the dependencies a bit more lenient with 2.1.0b1. If anything causing issues, please let us know. I'll close this one for now.
