### ISSUE TITLE
Update soda --help for new `soda create yourwarehousetype` command

### ISSUE THREAD

**Issue by janet-can** [sodadata/soda-sql#259]
**Describe the bug**
When I use the command line for help, the output describes the commands, one of which is `soda create`. With the new warehouse-specific install packages, we should update the output of the `soda --help` command to display `soda create yourwareshousetype`. 

**Context**
```shell
soda --help
Usage: soda [OPTIONS] COMMAND [ARGS]...

  Soda CLI version 2.1.0b1

Options:
  --help  Show this message and exit.

Commands:
  analyze  Analyzes tables in the warehouse and creates scan YAML files...
  create   Creates a new warehouse.yml file and prepares credentials in
           your...

  scan     Computes all measurements and runs all tests on one table.
```

**Comment by vijaykiran** [comment]
@janet-can  I don't understand what should be changed? Do you mean the create help text should change?

**Comment by janet-can** [comment]
actually, nevermind. I realize now that `soda create --help` does not require warehouse type. User error! Closing :)
