### ISSUE TITLE
[sql server] Soda analyse  can't handle columns that are reserved names

### ISSUE THREAD

**Issue by pbuxtonccuk** [sodadata/soda-sql#356]
**Describe the bug**
Running soda analyze against a SQLServer database where some tables have columns with the same name as a reserved keyword fails with 'incorrect syntax'

There should be an option to encapsulate columns names with [], or it should do it  always

**To Reproduce**
1. Create a test database with a table containing the columns 'myid' and a column named 'order'
1. Modify warehouse.yml and the credentials yml to suit to conenct to the database
2. Run `soda analyze'

**OS**: 
Centos 7

**Python Version**:
3.8.1

**Soda SQL Version**:
Latest Soda SQLServer beta

**Warehouse Type**:
SQLServer 2017

**Comment by pbuxtonccuk** [comment]
I am aware that I could manually create the various scan.ymls per table, but I'd rather not.  There's a lot if them .........

**Comment by vijaykiran** [comment]
Fixed in latest tag!
