### ISSUE TITLE
Document scan.yml

### ISSUE THREAD

**Issue by tombaeyens** [sodadata/soda-sql#43]
Currently only the properties are listed in docs/scan.md
The goal is that this page becomes the reference doc for scan yaml files.
Add some more context describing the properties.

**Comment by dirkgroenen** [comment]
I think it has already been extended a little in the last few days/weeks, which is good. Maybe some examples wouldn't hurt either.

**Comment by tombaeyens** [comment]
Closing as @janet-can is on it.
