### ISSUE TITLE
Make CI faster!

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-sql#456]

**Comment by fakirAyoub** [comment]
We will work on this and finalize it for V3.
Workflow:
1. Have an EC2 instance with all the dependencies pre-installed.
2. Use self-hosted runners (running instances of this EC2 instance)
3. Run the build/tests
4. Destroy the running instance
5. If/when necessary, have one instance per warehouse; this will also help trigger warehouses independently.
