### ISSUE TITLE
soda scan error exit 0

### ISSUE THREAD

**Issue by cedric-orange** [sodadata/soda-sql#620]
**Describe the bug**
When I am running `soda scan --offline ./warehouse.yml ./tables/my_table.yml` and some tests are in error, command return code is not 1, but 0.

**To Reproduce**
1. Create a new test in `scan.yml` with a fail test
2. Run `soda scan ...`
3. check return code

Return code should not be 0.

**OS**: Linux
**Python Version**: Python 3.9.9
**Soda SQL Version**: Soda CLI version 2.1.1
**Warehouse Type**: bigquery

**Comment by vijaykiran** [comment]
Looks like this is caused by `@soda_trace` wrapper.
