### ISSUE TITLE
Error in soda-sql:tests doc

### ISSUE THREAD

**Issue by mathissedestrooper** [sodadata/soda-sql#72]
Hi team,

There seems to be an error in the soda-sql:tests doc: https://docs.soda.io/soda-sql/documentation/tests.html. More specifically, the sample snippet in the column test seems to be wrong.

In the scan.yml the **tests and validity_format** don't need a "-": 

![image](https://user-images.githubusercontent.com/77669982/106634335-fb854800-657f-11eb-9e96-b9d73f7b5b65.png)

Expected working snippet:

> table_name: yourtable
metrics:
    - row_count
    - missing_percentage
    - invalid_percentage
columns:
    start_date:
        validity_format: date_eu
        tests:
            - invalid_percentage < 2.0

Thanks :)

**Comment by tombaeyens** [comment]
fixed
